### PR TITLE
Add Oh No Type Co guide to Outlines Useful Links

### PR DESCRIPTION
**Pull request by eliheuer**
This came up in this Add Font issue: https://github.com/google/fonts/issues/6634

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Hi @eliheuer, I've noticed now that we are referring to Font quality in at least three places:
- The [New Fonts requirements](https://googlefonts.github.io/gf-guide/onboarding.html#new-fonts)
- The  [Quality Assurance tools and resources](https://googlefonts.github.io/gf-guide/qa.html) where the Oh No Type Teaching resource is also listed under the QA's page useful links, below the Outlines Quality sub-section.
- And here in the Outline Quality specific article

We could either add this specific vector's drawing link here and leave the others in the QA tools chapter, centralize them in one of the pages, or at least add a cross-reference between the three pages. E.g. mentioning at least one of the QA pages in the New Fonts requirements page.

What do you think is best?

**Review by vv-monsalve — APPROVED** [review]

**Comment by eliheuer** [comment]
This link is just to the outline quality blog from Oh No, but the link on `qa.html` is to ALL the blog posts from them, with this one on the second page where it might not be seen. So I think its fine to have both links where they are.

But linking to both the QA and Outlines sections from the New Fonts requirements page seems like a good idea if that is not already happening.

**Comment by vv-monsalve** [comment]
Agree. 
And no, if I saw it correctly, there has yet to be a reference to the Outlines Quality in the New Fonts requirements. So it would be a good addition indeed.

**Comment by eliheuer** [comment]
I'm making a simple PR now and will ask for a review.

**Comment by eliheuer** [comment]
Ok, I made a new PR doing what @vv-monsalve suggested above: https://github.com/googlefonts/googlefonts.github.io/pull/108

**Pull request merged**
